name: Deploy Full Stack App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout Code
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Configure AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 3️⃣ Login to ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.ECR_BACKEND }}

    # 4️⃣ Build & Push Backend
    - name: Build & Push Backend
      run: |
        docker build -t backend-app ./backend
        docker tag backend-app:latest ${{ secrets.ECR_BACKEND }}:latest
        docker push ${{ secrets.ECR_BACKEND }}:latest

    # 5️⃣ Build & Push Frontend
    - name: Build & Push Frontend
      run: |
        docker build -t frontend-app ./frontend
        docker tag frontend-app:latest ${{ secrets.ECR_FRONTEND }}:latest
        docker push ${{ secrets.ECR_FRONTEND }}:latest

    # 6️⃣ Deploy on EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) 211578345503.dkr.ecr.us-east-1.amazonaws.com

          docker pull ${{ secrets.ECR_BACKEND }}:latest
          docker pull ${{ secrets.ECR_FRONTEND }}:latest

          docker stop backend frontend || true
          docker rm backend frontend || true

          docker run -d --name backend -p 5000:5000 ${{ secrets.ECR_BACKEND }}:latest
          docker run -d --name frontend -p 80:80 ${{ secrets.ECR_FRONTEND }}:latest
